name: docker-build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
    branches:
      - 'master'
      - 'staging'
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU for multi-platform build
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}},prefix=release-,enable=true
            type=raw,priority=1000,value=latest,enable=${{ github.ref == 'refs/heads/master' }}
            type=ref,event=branch

      - name: Push release
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: scanservjs-user2001
          build-args: |
            UID=1000
            GID=1000
          platforms: linux/amd64,linux/arm64,linux/arm/v7
